### ISSUE TITLE
动画问题

### ISSUE THREAD

**Issue by lvtanxi** [yipianfengye/android-adDialog#2]
你好，不知道是我的个例还是什么，点击按钮dialog要等好一会才出现。

**Comment by teemo927** [comment]
我也有一样的问题。等待时间比较久1.5s左右

**Comment by juhuacha18** [comment]
哥们 看过源码了吗？  源码里面写着呢！！！

// 延迟1s展示，为了避免ImageLoader还为加载完缓存图片时就展示了弹窗的情况
new Handler().postDelayed(new Runnable() {
       @Override
       public void run() {
             animDialogUtils.show(animType, bounciness, speed);
       }
}, 1000);

就在AdManager 122行代码

**Comment by chenxi0203** [comment]
去掉这个延迟1s感觉第一次也要1s后才弹出来，后面就快啦。
