### ISSUE TITLE
背景出现了，图没有出现

### ISSUE THREAD

**Issue by haojingliu** [yipianfengye/android-adDialog#7]
把sample code放在自己的app中ad pic无法显示，请问可能有什么情况呢？
![image](https://cloud.githubusercontent.com/assets/3175019/18656794/e3e05b84-7f26-11e6-9cc4-ca129f5bec9c.png)

Log里有09-20 03:49:32.641 10636-10636/com.gogosu.gogosuandroid I/dalvikvm: Could not find method android.widget.Spinner.getPopupContext, referenced from method android.support.v7.widget.AppCompatSpinner.getPopupContext
09-20 03:49:32.641 10636-10636/com.gogosu.gogosuandroid W/dalvikvm: VFY: unable to resolve virtual method 22074: Landroid/widget/Spinner;.getPopupContext ()Landroid/content/Context;
09-20 03:49:32.641 10636-10636/com.gogosu.gogosuandroid D/dalvikvm: VFY: replacing opcode 0x6f at 0x000b
09-20 03:49:32.645 10636-10636/com.gogosu.gogosuandroid I/ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
09-20 03:49:32.645 10636-10636/com.gogosu.gogosuandroid I/dalvikvm: Could not find method android.widget.PopupWindow.showAsDropDown, referenced from method android.support.v7.widget.AppCompatPopupWindow.showAsDropDown
09-20 03:49:32.645 10636-10636/com.gogosu.gogosuandroid W/dalvikvm: VFY: unable to resolve virtual method 21884: Landroid/widget/PopupWindow;.showAsDropDown (Landroid/view/View;III)V
09-20 03:49:32.645 10636-10636/com.gogosu.gogosuandroid D/dalvikvm: VFY: replacing opcode 0x6f at 0x000d
09-20 03:49:32.677 10636-10636/com.gogosu.gogosuandroid W/EGL_genymotion: eglSurfaceAttrib not implemented
09-20 03:50:36.253 10636-10742/com.gogosu.gogosuandroid D/dalvikvm: GC_FOR_ALLOC freed 680K, 7% free 12180K/12972K, paused 6ms, total 6ms

**Comment by yipianfengye** [comment]
应该是下载失败了，你申请了网络权限了么？

**Comment by haojingliu** [comment]
申请了，加的这个
 `<uses-permission android:name="android.permission.INTERNET" />`

**Comment by yuzhongrong** [comment]
我也出现这个问题了 @haojingliu 你是怎么解决的

**Comment by haojingliu** [comment]
@yuzhongrong 时间太长了不记得了，不好意思【手动捂脸】
