### ISSUE TITLE
  急问。。

### ISSUE THREAD

**Issue by 1184104588** [yipianfengye/android-adDialog#9]
只弹出一个透明层，没有加载图片。。什么原因呢。。

**Comment by yipianfengye** [comment]
添加网络权限了么？


原始邮件
发件人:1184104588notifications@github.com
收件人:yipianfengye/android-adDialogandroid-adDialog@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年3月1日(周三) 09:31
主题:[yipianfengye/android-adDialog] 急问。。 (#9)


只弹出一个透明层，没有加载图片。。什么原因呢。。

**Comment by 1184104588** [comment]
网络权限是添加了的。

**Comment by 1184104588** [comment]
其他还有什么原因会出现这样的问题吗？

**Comment by hzyzygg** [comment]
我也是这样，只弹出一个透明层，图片没加载出来，你是怎么解决的？

**Comment by yhh5158** [comment]
我的也是只有一个弹层 没有图片 有没有解决的

**Comment by Mexicande** [comment]
这个问题是因为作者库中使用了Facebook的Fresco，而且使用混淆后，Fresco需要是添加混淆规则，否者不起作用，https://www.fresco-cn.org/docs/proguard.html  Fresco的中文网也有说明！
